# Generated by Django 5.2.9 on 2025-12-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='categoria',
        ),
        migrations.AddField(
            model_name='jogo',
            name='categoria',
            field=models.ManyToManyField(blank=True, related_name='jogos', to='app.categoria'),
        ),
    ]
