# Generated by Django 5.2.9 on 2025-12-17 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_jogo_categoria_jogo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
