# Generated by Django 5.2.9 on 2025-12-14 18:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_categoria_destaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcompra',
            name='nome_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jogo',
            name='banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jogo',
            name='deletado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jogo',
            name='desconto',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('finalizada', 'Finalizada'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='jogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.jogo'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='icone',
            field=models.ImageField(blank=True, default='icones/bobas.webp', null=True, upload_to='icones/'),
        ),
    ]
