# Generated by Django 5.2.9 on 2025-12-14 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_itemcompra_nome_snapshot_jogo_banner_jogo_deletado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, default='icones/bobas.webp', null=True, upload_to='fotos-usuarios/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minha_foto', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
        ),
    ]
