# Generated by Django 5.2.9 on 2025-12-15 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_fotoperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='autoria',
            field=models.CharField(default='Desconhecido', max_length=200),
        ),
        migrations.AddField(
            model_name='jogo',
            name='lancamento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='jogo',
            name='plataforma',
            field=models.CharField(choices=[('pc', 'PC')], default='pc', max_length=20),
        ),
        migrations.AlterField(
            model_name='fotoperfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='fotos-usuarios/bobas.webp', null=True, upload_to='fotos-usuarios/'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='icone',
            field=models.ImageField(blank=True, default='icones/birdgame.webp', null=True, upload_to='icones/'),
        ),
    ]
