# Generated by Django 5.2.9 on 2025-12-15 19:45

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_jogo_autoria_jogo_lancamento_jogo_plataforma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=app.models.ImagemExtra.upload_to_imagem)),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem para exibição')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_extras', to='app.jogo')),
            ],
            options={
                'ordering': ['ordem', '-data_upload'],
            },
        ),
    ]
