# Generated by Django 5.2.9 on 2025-12-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_imagemextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='pre_lancamento',
            field=models.BooleanField(default=False),
        ),
    ]
